### ISSUE TITLE
Using with other fan manufacturers?

### ISSUE THREAD

**Issue by WotAGitUR** [moifort/homebridge-create-fan#10]
I took me a while to realize that Create was a fan manufacturer :)
I'm using the latest version (0.0.81) of your plugin in my homebridge 1.6.1 server, but my fan is just a generic Tuya based ceiling fan from a company called Eogifee.
I was curious how you made this plugin specific to Create to see if I could tweak it to work with my ceiling fan.
All of the steps you linked to to get the device to show up all work, but when I restart homebridge I get this error. 

Connection failed Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /var/lib/homebridge/node_modules/homebridge-create-ceiling-fan/node_modules/tuyapi/index.js:1062:13
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-create-ceiling-fan/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)

I have the fan set with a static ip address, but can't see where to configure it.
Any pointers you  have would be much appreciated ;)

**Comment by moifort** [comment]
Hello,

Maybe you have the same problem explained [here](https://github.com/moifort/homebridge-create-fan/issues/11#issue-1805996644), your fan can manage brightness ? If not, I can add an option to disable brightness and have a toggle instead, What do you think ?

**Comment by WotAGitUR** [comment]
Thank you for replying :)
Yes I think you are correct, it sounds very similar indeed.
I think that because my fan isn’t a Create that most of the option codes are incorrect, so while it appears in Homebridge it doesn’t start the fan.
I think I have the codes from TinyTua so was going to try figuring out how to adjust the plug-in locally to see if I could get it going

**Comment by ruaandeysel** [comment]
Hi @moifort, I stumbled upon your plugin and it looks great. I have ceiling fans that uses a Tuya wifi adapter and the DPS / DPID are as follows:

DPID | Description | Example
-- | -- | --
1 | Power | ON or OFF
2 | Mode | NORMAL, NATURE or SLEEP
3 | Fan Speed | 1,2,3,4 or 5
22 | Timer | 1 Hour
8 | Direction | FORWARD or REVERSE
15 | Light | ON or OFF
16 | Brightness | 1,2,3,4,5 

Product ID

vzj97d3m05yjhchn

Were in your code do I need to update the DPS values to work with my fans?

I will appreciate the help.
