### ISSUE TITLE
Paramétrage du PlugIn

### ISSUE THREAD

**Issue by GotierLdl** [moifort/homebridge-create-fan#12]
Bonjour,

Devant recevoir mon ventilateur Create WINDCALM j'ai une question pour éviter de tout devoir réinitialiser.

Dois t-on associé le ventilateur à l'application Create ou bien directement via l'application Tuya ?

Si c'est via Create, la méthode est la même pour récupérer l'id et la key via Tuya IoT ?

Merci par avance.

**Comment by GotierLdl** [comment]
Bon, application apparaier sur Create, impossible d'avoir la local key : 
![image](https://github.com/moifort/homebridge-create-fan/assets/55806386/8b484296-e9ce-45c8-98af-d5fcdcf64c93)

Y'a t-il a moyen de la récuper sans passer par Tuya iot ?

**Comment by moifort** [comment]
Je ne sais pas si il y a d'autre moyen. Avez vous bien essayer le tutoriel https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md ?

**Comment by GotierLdl** [comment]
Pour cela il faut avoir appairer sur l'application Tuya non. De votre côté vous etes passé par Create ou bien Tuya app ?

**Comment by KevinMllrd** [comment]
Bonjour, j'ai suivi le pdf, mais je pense ne trouve toujours pas ID & Key à saisir dans le plugin. 
Je ne trouve pas comment procéder à l'étape 4 : On the command line, run tuya-cli wizard. It will prompt you for required information, and will then list out all your device names, IDs, and keys for use with TuyAPI. Copy and save this information to a safe place for later reference.

Pouvez-vous m'apporter des précisions sur ce point ?

Homebridge retourne l'erreur suivante : TypeError: Key is missing or incorrect.
    at new TuyaDevice (/usr/local/lib/node_modules/homebridge-create-ceiling-fan/node_modules/tuyapi/index.js:78:13)
    at new FanAccessory (file:///usr/local/lib/node_modules/homebridge-create-ceiling-fan/src/accessory.ts:59:23)
    at HomebridgeCreateCeilingFan.discoverDevices (file:///usr/local/lib/node_modules/homebridge-create-ceiling-fan/src/platform.ts:53:9)
    at HomebridgeAPI.<anonymous> (file:///usr/local/lib/node_modules/homebridge-create-ceiling-fan/src/platform.ts:38:12)
    at HomebridgeAPI.emit (node:events:518:28)
    at HomebridgeAPI.signalFinished (file:///usr/local/lib/node_modules/homebridge/src/api.ts:244:10)
    at ChildBridgeFork.startBridge (file:///usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:197:14)
[7/16/2025, 10:38:06 PM] [Create Ceiling Fan] Child bridge ended (code 1, signal null). The child bridge ended unexpectedly, which is normally due to the plugin not catching its errors properly. Please report this to the plugin developer by clicking on the 'Report An Issue' option in the plugin menu dropdown from the Homebridge UI. If there are related logs shown above, please include them in your report.
[7/16/2025, 10:38:06 PM] [Create Ceiling Fan] Child bridge will no longer restart after failing 5 times, you will need to manually start this child bridge from the Homebridge UI.

**Comment by KevinMllrd** [comment]
Bonjour,

Comment avez vous fait pour avoir un curseur permettant de régler la vitesse du ventilateur et l'intensité de la lumière ?
De mon côté, je n'ai que la fonction ON/OFF ce qui n'est pas super pratique.
