### ISSUE TITLE
Code 143

### ISSUE THREAD

**Issue by EzeikieI** [moifort/homebridge-create-fan#16]
Salut,

Après plusieurs réinstallations du plugin, toujours la même erreur et HOMEBRIDGE redémarre à chaque fois. 

Même problème avec les deux modèles de ventilateur de chez CREATE - WIND STYLANCE & WIND CLEAR achetés en avril. 

Ci-dessous le code si cela peut permettre de comprendre. Si tu as une solution, je suis preneur ! Merci.

[01/05/2024, 21:22:30] [HB Supervisor] Started Homebridge v1.8.1 with PID: 1949
[01/05/2024, 21:22:32] Loaded config.json with 0 accessories and 2 platforms.
[01/05/2024, 21:22:32] Loaded 0 cached accessories from cachedAccessories.
[01/05/2024, 21:22:32] ---
[01/05/2024, 21:22:32] Loaded plugin: homebridge-create-ceiling-fan@0.0.89
[01/05/2024, 21:22:32] Registering platform 'homebridge-create-ceiling-fan.HomebridgeCreateCeilingFan'
[01/05/2024, 21:22:32] ---
[01/05/2024, 21:22:32] Loading 2 platforms...
[01/05/2024, 21:22:32] [Create Ceiling Fan] Initializing HomebridgeCreateCeilingFan platform...
[01/05/2024, 21:22:32] [Create Ceiling Fan] Adding new ceiling fan: bf26634f896db286a3bps0 Bureau true
[01/05/2024, 21:22:32] [Create Ceiling Fan] Connecting...
[01/05/2024, 21:22:32] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at Hash.update (node:internal/crypto/hash:107:11)
    at Object.generate (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)
    at HomebridgeCreateCeilingFan.discoverDevices (/var/lib/homebridge/node_modules/homebridge-create-ceiling-fan/dist/platform.js:40:44)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-create-ceiling-fan/dist/platform.js:31:18)
    at HomebridgeAPI.emit (node:events:517:28)
    at HomebridgeAPI.signalFinished (/var/lib/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:178:14)
[01/05/2024, 21:22:32] Got SIGTERM, shutting down Homebridge...
[01/05/2024, 21:22:33] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:143:45)
    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:187:10)
    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:517:28)
    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[01/05/2024, 21:22:37] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[01/05/2024, 21:22:42] [HB Supervisor] Restarting Homebridge...
[01/05/2024, 21:22:42] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[01/05/2024, 21:22:42] [HB Supervisor] Started Homebridge v1.8.1 with PID: 1963
[01/05/2024, 21:22:43] [Homebridge UI] Changes to config.json saved.
[01/05/2024, 21:22:44] [Homebridge UI] Homebridge restart request received
[01/05/2024, 21:22:44] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[01/05/2024, 21:22:44] [Homebridge UI] Sending SIGTERM to Homebridge
[01/05/2024, 21:22:44] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTERM
[01/05/2024, 21:22:49] [HB Supervisor] Restarting Homebridge...
[01/05/2024, 21:22:49] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[01/05/2024, 21:22:49] [HB Supervisor] Started Homebridge v1.8.1 with PID: 1974
[01/05/2024, 21:22:51] Loaded config.json with 0 accessories and 2 platforms.
[01/05/2024, 21:22:51] Loaded 1 cached accessories from cachedAccessories.
[01/05/2024, 21:22:51] ---
[01/05/2024, 21:22:51] Disabled plugin: homebridge-create-ceiling-fan@0.0.89
[01/05/2024, 21:22:51] ---
[01/05/2024, 21:22:51] Loading 2 platforms...
[01/05/2024, 21:22:51] Ignoring config for the platform "HomebridgeCreateCeilingFan" in your config.json as the plugin "homebridge-create-ceiling-fan" has been disabled.
[01/05/2024, 21:22:51] Failed to find plugin to handle accessory Bureau
[01/05/2024, 21:22:51] Removing orphaned accessory Bureau
Setup Payload:
X-HM://0024W4E7P3K9N
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 859-79-381 │     
    └────────────┘     
                       
[01/05/2024, 21:22:51] Homebridge v1.8.1 (HAP v0.12.0) (Homebridge ABD6) is running on port 51091.

**Comment by EzeikieI** [comment]
J'ai trouvé...
J'ai supprimé les espaces dans le SSID de ma wifi... 

> Salut,
> 
> Après plusieurs réinstallations du plugin, toujours la même erreur et HOMEBRIDGE redémarre à chaque fois.
> 
> Même problème avec les deux modèles de ventilateur de chez CREATE - WIND STYLANCE & WIND CLEAR achetés en avril.
> 
> Ci-dessous le code si cela peut permettre de comprendre. Si tu as une solution, je suis preneur ! Merci.
> 
> [01/05/2024, 21:22:30] [HB Supervisor] Started Homebridge v1.8.1 with PID: 1949 [01/05/2024, 21:22:32] Loaded config.json with 0 accessories and 2 platforms. [01/05/2024, 21:22:32] Loaded 0 cached accessories from cachedAccessories. [01/05/2024, 21:22:32] --- [01/05/2024, 21:22:32] Loaded plugin: homebridge-create-ceiling-fan@0.0.89 [01/05/2024, 21:22:32] Registering platform 'homebridge-create-ceiling-fan.HomebridgeCreateCeilingFan' [01/05/2024, 21:22:32] --- [01/05/2024, 21:22:32] Loading 2 platforms... [01/05/2024, 21:22:32] [Create Ceiling Fan] Initializing HomebridgeCreateCeilingFan platform... [01/05/2024, 21:22:32] [Create Ceiling Fan] Adding new ceiling fan: bf26634f896db286a3bps0 Bureau true [01/05/2024, 21:22:32] [Create Ceiling Fan] Connecting... [01/05/2024, 21:22:32] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined at new NodeError (node:internal/errors:405:5) at Hash.update (node:internal/crypto/hash:107:11) at Object.generate (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11) at HomebridgeCreateCeilingFan.discoverDevices (/var/lib/homebridge/node_modules/homebridge-create-ceiling-fan/dist/platform.js:40:44) at HomebridgeAPI. (/var/lib/homebridge/node_modules/homebridge-create-ceiling-fan/dist/platform.js:31:18) at HomebridgeAPI.emit (node:events:517:28) at HomebridgeAPI.signalFinished (/var/lib/homebridge/node_modules/homebridge/src/api.ts:275:10) at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:178:14) [01/05/2024, 21:22:32] Got SIGTERM, shutting down Homebridge... [01/05/2024, 21:22:33] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet! at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11) at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:143:45) at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:187:10) at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:94:12) at process.emit (node:events:517:28) at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21) [01/05/2024, 21:22:37] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null [01/05/2024, 21:22:42] [HB Supervisor] Restarting Homebridge... [01/05/2024, 21:22:42] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution [01/05/2024, 21:22:42] [HB Supervisor] Started Homebridge v1.8.1 with PID: 1963 [01/05/2024, 21:22:43] [Homebridge UI] Changes to config.json saved. [01/05/2024, 21:22:44] [Homebridge UI] Homebridge restart request received [01/05/2024, 21:22:44] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process [01/05/2024, 21:22:44] [Homebridge UI] Sending SIGTERM to Homebridge [01/05/2024, 21:22:44] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTERM [01/05/2024, 21:22:49] [HB Supervisor] Restarting Homebridge... [01/05/2024, 21:22:49] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution [01/05/2024, 21:22:49] [HB Supervisor] Started Homebridge v1.8.1 with PID: 1974 [01/05/2024, 21:22:51] Loaded config.json with 0 accessories and 2 platforms. [01/05/2024, 21:22:51] Loaded 1 cached accessories from cachedAccessories. [01/05/2024, 21:22:51] --- [01/05/2024, 21:22:51] Disabled plugin: homebridge-create-ceiling-fan@0.0.89 [01/05/2024, 21:22:51] --- [01/05/2024, 21:22:51] Loading 2 platforms... [01/05/2024, 21:22:51] Ignoring config for the platform "HomebridgeCreateCeilingFan" in your config.json as the plugin "homebridge-create-ceiling-fan" has been disabled. [01/05/2024, 21:22:51] Failed to find plugin to handle accessory Bureau [01/05/2024, 21:22:51] Removing orphaned accessory Bureau Setup Payload: X-HM://0024W4E7P3K9N Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
> 
> ```
> ┌────────────┐     
> │ 859-79-381 │     
> └────────────┘     
> ```
> 
> [01/05/2024, 21:22:51] Homebridge v1.8.1 (HAP v0.12.0) (Homebridge ABD6) is running on port 51091.

**Comment by EzeikieI** [comment]
Il suffisait de supprimer les espaces du SSID de la wifi ...

**Comment by moifort** [comment]
Wow, bonne intuition ! 

Enjoy!

**Comment by EzeikieI** [comment]
Salut,
Tout fonctionne nickel, jusqu'à ce que j'utilise l'interrupteur pour allumer ou éteindre et partir de ce moment là, j'ai un code erreur 60 qui apparait : 

`[02/05/2024, 11:28:03] TypeError: Cannot read properties of undefined (reading '60')
    at TuyaDevice.stateHook (/var/lib/homebridge/node_modules/homebridge-create-ceiling-fan/dist/platformAccessory.js:53:34)
    at TuyaDevice.emit (node:events:529:35)
    at TuyaDevice._packetHandler (/var/lib/homebridge/node_modules/homebridge-create-ceiling-fan/node_modules/tuyapi/index.js:840:12)
    at /var/lib/homebridge/node_modules/homebridge-create-ceiling-fan/node_modules/tuyapi/index.js:643:39
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-create-ceiling-fan/node_modules/tuyapi/index.js:639:15)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Socket.Readable.push (node:internal/streams/readable:278:10)`

Cela fait planter HOMEBRIDGE et plus rien ne fonctionne...

La solution est de réinitialiser aux paramètres d'usine en supprimant le ventilo qui a été éteint avec l'interrupteur de l'app tuya, réappairé le ventilo, reprendre la clé qui change et reconfigurer le plugin. Ou ne plus utiliser l'interrupteur et laisser le ventilo alimenté 24/24... Mais pas pratique.... 

A moins qu'il y ait une solution soft? 

Merci.
