### ISSUE TITLE
Error : Error: Error from socket: read ECONNRESET

### ISSUE THREAD

**Issue by ThibaultTourailles** [moifort/homebridge-create-fan#18]
Connection to the ceiling fan is not properly working. In the log, there's a notification that connection has been reset.
I've followed the steps in https://github.com/jasonacox/tinytuya/tree/master#setup-wizard---getting-local-keys, I managed to get the keys. 
I managed to test the fetched information with this python script:
```python
import tinytuya

# Connect to Device
d = tinytuya.OutletDevice(
    dev_id='<DEVICE_ID>',
    address='<IP_ADDRESS>',
    local_key="<LOCAL_KEY>",
    version=3.4)

data = d.set_status(True, 20)
if data:
    print('set_status() result %r' % data)
```
And it turned the light on.

**Logs:**

```
[7/2/2024, 2:43:40 PM] [Create Ceiling Fan] Error : Error: Error from socket: read ECONNRESET
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-create-ceiling-fan/node_modules/tuyapi/index.js:651:26)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[7/2/2024, 2:43:40 PM] [Create Ceiling Fan] Try to connect
[7/2/2024, 2:43:40 PM] [Create Ceiling Fan] Connecting...
[7/2/2024, 2:43:40 PM] [Create Ceiling Fan] Connected
[7/2/2024, 2:43:40 PM] [Create Ceiling Fan] Disconnected... Try to connect
[7/2/2024, 2:43:40 PM] [Create Ceiling Fan] Connecting...
[7/2/2024, 2:43:40 PM] [Create Ceiling Fan] Connected
[7/2/2024, 2:43:40 PM] [Create Ceiling Fan] Error : Error: Error from socket: read ECONNRESET
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-create-ceiling-fan/node_modules/tuyapi/index.js:651:26)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge C2C7",
        "username": "<USERNAME>",
        "port": 51274,
        "pin": "<PIN>",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Create Ceiling Fan",
            "devices": [
                {
                    "id": "<SAME_ID_AS_PYTHON_SCRIPT>",
                    "key": "<SAME_KEY_AS_PYTHON_SCRIPT>",
                    "ip": "<SAME_IP_AS_PYTHON_SCRIPT>",
                    "version": "3.4",
                    "name": "Ceiling Fan",
                    "hasLight": true
                }
            ],
            "platform": "HomebridgeCreateCeilingFan"
        }
    ]
}

```

**Environment:**

* **Plugin Version**: 0.0.89
* **Homebridge Version**: 1.8.3
* **Node.js Version**: 20.7.0
* **NPM Version**: npm -v
* **Operating System**: macOS 12.7.4

**Comment by Pi88no** [comment]
It worked for two days, but today I also get this error message. 

```
 [7/16/2024, 12:55:44 PM] [Deckenventilator] Error : Error: Error from socket: read ECONNRESET
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-create-ceiling-fan/node_modules/tuyapi/index.js:651:26)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[7/16/2024, 12:55:44 PM] [Deckenventilator] Try to connect
[7/16/2024, 12:55:44 PM] [Deckenventilator] Connecting...
[7/16/2024, 12:55:44 PM] [Deckenventilator] Connection failed Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:218:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
[7/16/2024, 12:55:44 PM] [Deckenventilator] Retry in 1 minute
```

**Comment by RedJohn14** [comment]
I get exact the same error today. Plugin not working.

**Comment by Nicode70** [comment]
same thing for me here:

[2/12/2025, 8:14:02 AM] [Create Ceiling Fan] Device connected!
[2/12/2025, 8:14:02 AM] [Create Ceiling Fan] Error : Error: Error from socket: read ECONNRESET
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-create-ceiling-fan/node_modules/tuyapi/index.js:686:26)
    at Socket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:90:21)

Any clue on how to solve this?

**Comment by pandizajner** [comment]
I'm having the same issue for a long time. Restarting HB helps, but this works only for a while (few hours / one day). 

```
[09/03/2025, 20:08:57] [Create Ceiling Fan] Device connected!
[09/03/2025, 20:08:57] [Create Ceiling Fan] Error : Error: Error from socket: read ECONNRESET
    at Socket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-create-ceiling-fan/node_modules/tuyapi/index.js:686:26)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Then I get the above in the console. A couple times a day. I'm not sure what the recalling is related to.

**Comment by Fredovic** [comment]
Same error here. After restarting it works just for a few hours… Any clue or other plugin alternative?

**Comment by Pi88no** [comment]
> Same error here. After restarting it works just for a few hours… Any clue or other plugin alternative?

I used the Tuya plugin. To use this, install the Tuya Smart app and integrate the fans into the app. 

I have created scenes that control the fan, e.g. a scene: Fan ON + turn right + level 2. Another scene: Fan OFF

The scenes are then integrated into Apple Home via the HB plugin. 

Disadvantage: The status of the Ventialors is not transmitted. Unfortunately, I don't remember more precisely, because I don't use the fans anymore. Possibly further steps are necessary, I think you had to set yourself up as a developer in the Tuya app.

**Comment by ChristianPorsche** [comment]
Same problem

**Comment by hendrixou** [comment]
Exactly the same problem !!!

**Comment by hendrixou** [comment]
The same problem ecoreset

**Comment by moifort** [comment]
I aI apologize for the delayed (very delayed) response. I completely refactored the plugins and resolved all major issues after running for over a month. Could you test the new version and let me know if it’s work ?

PS: I strongly suggest using the device’s IP address instead of its ID, since relying on the ID may raise disconnection issue. Just be sure to set your device’s IP through your DHCP settings.

**Comment by hendrixou** [comment]
Still not working …

**Comment by moifort** [comment]
Are you controlling the fan through another Tuya app too? From what I've read on the forums, the official Tuya app can drop all active connections, including the plugin's. There's normally a reconnection strategy that should recover automatically.
Note that if another plugin restarts Homebridge, it won't speed up reconnection — it isn't instant, so the plugin needs a bit of time to reconnect after a reboot.
